name:                cormorant
version:             0.1.0.0
github:              "ecthiender/cormorant"
license:             BSD3
author:              "Anon Ray"
maintainer:          "rayanon004@gmail.com"
copyright:           "2018 Anon Ray"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://gitlab.com/rayanon/cormorant#readme>

dependencies:
- base >= 4.7 && < 5
- text
- unordered-containers
- time
- mtl
- wreq
- lens
- aeson
- aeson-casing
- bytestring
- wai
- Spock-core
- http-types

library:
  source-dirs: src

ghc-options:
- -O2
- -Wall

executables:
  cormorant:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    dependencies:
    - cormorant

tests:
  cormorant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cormorant
